---
keybinding:
  LS_UP: 'LS_UP'
  LS_DOWN: 'LS_DOWN'
  LS_LEFT: 'LS_LEFT'
  LS_RIGHT: 'LS_RIGHT'
  LSB : 'LSB'
  RS_UP: 'RS_UP'
  RS_DOWN: 'RS_DOWN'
  RS_LEFT: 'RS_LEFT'
  RS_RIGHT: 'RS_RIGHT'
  RSB : 'RSB'
  UP: 'UP'
  DOWN: 'DOWN'
  LEFT: 'LEFT'
  RIGHT: 'RIGHT'
  R1: 'R1'
  R2: 'R2'
  L1: 'L1'
  L2: 'L2'
  X: 'X'
  Y: 'Y'
  A: 'A'
  B: 'B'
  start: 'start'
  select: 'select'
fullscreen: false
scaled: false
